web_app/views/auth.py
import functools
from flask import (
	Blueprint, flash, g, redirect, render_template, request, session, url_for
	)
from werkzeug.security import generate_password_hash, check_password_hash
from web_app.db import get_db

# Blueprints organize related views and code. The views and code are registered with the blueprint, 
# and the blueprint is registered with the application instance. 
bp = Blueprint('auth', __name__, url_prefix = '/auth')

@bp.route('/register', methods = ('GET', 'POST'))
def register():
	""" This function requests the form values of username and password. It then
	creates a database variable and an error variable for storing the username and passwords 
	from the form, and any errors to be flashed in the error var. If there is no error, the 
	user is added to the database. If there is, it flashed the error and returns the user to
	the register page. """
	if request.method == 'POST':
		username = request.form['username']
		password = request.form['password']
		db = get_db()
		error = None

		if not username:
			error = 'Username is required.'
		elif not password:
			error = 'Password is required'
		elif db.execute(
			'SELECT id FROM user where username = ?',
			(username,)
		).fetchone() is not None:
			error = 'User {} is already registered.'.format(username)

		if error is None:
			db.execute(
				'INSERT INTO user (username, password) VALUES (?, ?)',
				(username, generate_password_hash(password))
			)
			db.commit()
			return redirect(url_for('auth.login'))

		flash(error)

	return render_template('auth/register.html')

@bp.route('/login', methods = ('GET', 'POST'))
def login():
	if request.method == 'POST':
		username = request.form['username']
		password = request.form['password']

		db = get_db()
		error = None
		user = db.execute(
			'SELECT * FROM user WHERE username = ?', (username,)
		).fetchone()

		if user is None:
			error = 'Incorrect username.'
		elif not check_password_hash(user['password'], password):
			error = 'Incorrect password.'

		if error is None:
			session.clear()
			session['user_id'] = user['id']
			return redirect(url_for('cms.create'))

		flash(error)

	return render_template('auth/login.html')

@bp.before_app_request
def load_logged_in_user():
	""" This function gets the user id from the session dict. It then makes 
	it available to others views. It does this my adding the user_id to the
	special 'g' object. """
	user_id = session.get('user_id')

	if user_id is None:
		g.user = None
	else: 
		g.user = get_db().execute(
			'SELECT * FROM user WHERE id = ?', (user_id,)
		).fetchone()

@bp.route('/logout')
def logout():
	""" This function removes the user_id from the session """
	session.clear()
	return redirect(url_for('index'))

def login_required(view):
	""" This decorator returns a new view function that wraps the original view its 
	applied to. It checks if a user is logged in and redirects to the login page if not. """
	@functools.wraps(view)
	def wrapped_view(**kwargs):
		if g.user is None:
			return redirect(url_for('auth.login'))

		return view(**kwargs)
	return wrapped_view

web_app/views/category.py
from flask import (
	Blueprint, flash, g, redirect, render_template, request, url_for, current_app
)
import os

from werkzeug.exceptions import abort
from werkzeug.utils import secure_filename

from .auth import login_required
from web_app.db import get_db

# Giving this a url prefix, like the auth view, so 
bp = Blueprint('category', __name__, url_prefix = '/category')

@bp.route('/createcategory', methods=['GET', 'POST'])
@login_required
def createcategory():
	""" This view will display a simple page to create a sub-category based off of
	the categories available. The GET request portion will display the page with the categories
	available to select, with a text box next to it. The POST request portion will take the
	category selected and the sub_category and add it to the database. """
	if request.method == 'POST':
		category = request.form['category']
		sub_category = request.form['sub_category']
		error = None


		if not category:
			error = 'A category name must be selected.'

		if not sub_category:
			error = 'A subcategory name must be selected'

		# Ensure that the subcategory name is inserted into the database as all lowercase
		sub_category = sub_category.lower()

		if error is not None:
			flash(error)
		else:
			# If there are no errors, insert the data from the form into the database
			db = get_db()
			db.execute(
				'INSERT INTO category (category, sub_category)'
				' VALUES (?, ?)',
				(category, sub_category)
			)
			db.commit()

			return redirect(url_for('cms.index'))

	return render_template('category/createcategory.html')
	


@bp.route('/updatecategory', methods=['GET', 'POST'])
@login_required
def updatecategory():
	""" This view will handle updating the subcategory, if the name needs to be changed. """
	if request.method == 'POST':
		category_id = request.form['category_id']
		sub_category = request.form['sub_category']
		error = None

		if not sub_category:
			error = 'A new name is required for the subcategory.'

		if not category_id:
			error = 'A category must be selected.'

		if error is not None:
			flash(error)
		else:
			db = get_db()
			db.execute(
				'UPDATE category SET sub_category = ?'
				' WHERE id = ?',
				(sub_category, category_id)
			)

			db.commit()
			return redirect(url_for('cms.index'))

	else:
		# If the HTML request if GET, return the form page with the categories drop-down 
		# available for the author
		db = get_db()
	
		categories = db.execute(
			'SELECT id, category, sub_category'
			'	FROM category'
			'	ORDER BY category ASC, sub_category ASC'
		).fetchall()

	return render_template('category/updatecategory.html', categories=categories)

@bp.route('/deletecategory', methods=['GET', 'POST'])
@login_required
def deletecategory():
	""" This function will not have its own view, it will handle the delete input from the HTML
	category_delete page. Very similar to the delete() view in the cms.py page, but it has its 
	own view. """
	if request.method == 'POST':

		category_id = request.form['category_id']

		db = get_db()
		db.execute('DELETE FROM category WHERE id = ?', (category_id,))
		db.commit()
		return redirect(url_for('cms.index'))

	else:
		# If this is a get request, populate the categories object and pass it to the 
		# category_delete view. Also render the category_delete template. 
		db = get_db()
	
		categories = db.execute(
			'SELECT id, category, sub_category'
			'	FROM category'
			'	ORDER BY category ASC, sub_category ASC'
		).fetchall()

	return render_template('category/deletecategory.html', categories=categories)

web_app/views/cms.py
from flask import (
	Blueprint, flash, g, redirect, render_template, request, url_for, current_app
)
import os

from werkzeug.exceptions import abort
from werkzeug.utils import secure_filename

from .auth import login_required
from web_app.db import get_db

# Allowed extensions for files
ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}

# Giving this a url prefix, like the auth view, so 
bp = Blueprint('cms', __name__, url_prefix = '/cms')

# Determines if the filename is safe
def allowed_file(filename):
  return '.' in filename and \
    filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@bp.route('/index')
@login_required
def index():
	db = get_db()

	# Execute the select statement which gathers all the records of product
	items = db.execute(
		'SELECT i.id, i.author_id, i.created, i.item_name, i.picture_url, i.description, c.category, c.sub_category'
		' FROM user u JOIN item i ON u.id = i.author_id JOIN category c ON i.category_id = c.id'
		' ORDER BY i.created DESC'
	).fetchall()

	return render_template('cms/index.html', items=items)


@bp.route('/create', methods=['GET', 'POST'])
@login_required
def create():

	# If the submit buttom is pressed and HTML request is post...
	if request.method == 'POST':
		item_name = request.form['item_name']
		picture_url = request.form['picture_url']
		description = request.form['description']
		category_id = request.form['category_id']
		picture = request.files['picture']
		error = None

		# These are the different error detecting if statements
		if 'picture' not in request.files:
			error = 'No file detected.'
		if not allowed_file(picture.filename):
			error = 'That file name is not allowed.'
		if not picture.filename: 
			error = 'A file name is required.'
		if not picture_url:
			error = 'A picture url is required.'


		if error is not None:
			flash(error)
		else:
			# If there are no errors, insert the data from the form into the database
			db = get_db()
			db.execute(
				'INSERT INTO item (author_id, item_name, picture_url, description, category_id)'
				' VALUES (?, ?, ?, ?, ?)',
				(g.user['id'], item_name, picture_url, description, category_id)
			)
			db.commit()

			filename = secure_filename(picture.filename)
			picture.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))

			return redirect(url_for('cms.index'))

	else:

		# If the HTML request if GET, return the form page with the categories drop-down 
		# available for the author
		db = get_db()
	
		categories = db.execute(
			'SELECT id, category, sub_category'
			'	FROM category'
			'	ORDER BY category ASC, sub_category ASC'
		).fetchall()

	return render_template('cms/create.html', categories=categories)


def get_item(argId, check_author=True):
	""" This function fetches a item by id, and checks if the author matches the logged in user. """
	db = get_db()
	item = db.execute(
		'SELECT i.id, i.author_id, i.created, i.item_name, i.picture_url, i.description, c.category, c.sub_category'
		' FROM user u JOIN item i ON u.id = i.author_id JOIN category c ON i.category_id = c.id'
		' WHERE i.id = ?',
		(argId,)
	).fetchone()

	# 404 error means not found
	if item is None:
		abort(404, "Post id {0} doesn't exist.".format(argId))

	# 403 error means forbidden
	if check_author and item['author_id'] != g.user['id']:
		abort(403)
		#item['author_id']
	return item


# Flask will capture the id in the URL and pass it to argId argument as an integer.
@bp.route('/<int:argId>/update', methods=['GET', 'POST'])
@login_required
def update(argId):
	""" This view updates a single item in the database. TODO: Add the picture associated 
	with the item on to the delete form or view. """
	item = get_item(argId)

	if request.method == 'POST':
		item_name = request.form['item_name']
		picture_url = request.form['picture_url']
		description = request.form['description']
		category_id = request.form['category_id']
		error = None

		if not item_name:
			error = 'A name is required for the item.'

		if error is not None:
			flash(error)
		else:
			db = get_db()
			db.execute(
				'UPDATE item SET item_name = ?, picture_url = ?, description = ?, category_id = ?'
				' WHERE id = ?',
				(item_name, picture_url, description, category_id, argId)
			)

			db.commit()
			return redirect(url_for('cms.index'))

	else:
		# If the HTML request if GET, return the form page with the categories drop-down 
		# available for the author
		db = get_db()
	
		categories = db.execute(
			'SELECT id, category, sub_category'
			'	FROM category'
			'	ORDER BY category ASC, sub_category ASC'
		).fetchall()

	# This may or may not be correct. The original has the post (in this case item) object being
	# passed through to the rendered template. 
	# Original: return render_template('blog/update.html', post=post)
	return render_template('cms/update.html', categories=categories, item=item)


@bp.route('/<int:argId>/delete', methods=['POST',])
@login_required
def delete(argId):
	""" The delete view doesnt have its own template. Its a part of the update.html page, and
	posts to the /<id>/delete URL. It will only handle the post method and redirect to the 
	index view. """

	get_item(argId)
	db = get_db()
	db.execute('DELETE FROM item WHERE id = ?', (argId,))
	db.commit()
	return redirect(url_for('cms.index'))

web_app/views/home.py
from flask import (
	Blueprint, flash, g, redirect, render_template, request, url_for, current_app
)
import os

from werkzeug.exceptions import abort
from werkzeug.utils import secure_filename

from .auth import login_required
from web_app.db import get_db
from web_app.mail import send_email


# Blueprints organize related views and code. The views and code are registered with the blueprint, 
# and the blueprint is registered with the application instance. This blueprint doesn't require
# a url_prefix because its the main page of the site. This controller may be used for
# the entirety of the website, minus any sort of shopping cart. 
bp = Blueprint('home', __name__)

@bp.route('/', methods=['GET', 'POST'])
def index():
	# If a visitor sends in a request for corrospondence using the Home page form
	if request.method == 'POST':

		# Put user input into variables
		visitor_name = request.form['visitor_name']
		visitor_email = request.form['visitor_email']
		visitor_subject = request.form['visitor_subject']
		visitor_message = request.form['visitor_message']

		send_email(visitor_name, visitor_email, visitor_subject, visitor_message)

		return redirect(url_for('home.index'))

	else:
		# Create database object to query
		db = get_db()

		# Execute the select statement which gathers all the records of product. Order by category -> subcategory
		items = db.execute(
			'SELECT i.id, i.author_id, i.created, i.item_name, i.picture_url, i.description, c.category, c.sub_category'
			' FROM user u JOIN item i ON u.id = i.author_id JOIN category c ON i.category_id = c.id'
			' ORDER BY c.category ASC, c.sub_category ASC'
		).fetchall()

	return render_template('home.html', items=items)

web_app/templates/base.html
<!DOCTYPE HTML>
<title>{% block title %}{% endblock %} - Ford Glass</title>
<link rel="stylesheet" href="{{ url_for('static', filename='bulma.min.css')}}">
<!-- Font Awesome 5 -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/css/all.min.css">
<!-- Bulma-Social -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-social@1/bin/bulma-social.min.css">
<!-- Custom CSS code -->
<link rel="stylesheet" href="{{ url_for('static', filename='style.css')}}">
<meta name="viewport" content="width=device-width, initial-scale=1">
<nav class="navbar">
	<h1>Ford Glass</h1>
	<div class="navbar-end">
		{% if g.user %}
			<span class="navbar-item">{{ g.user['username'] }} </span>
			<div class="navbar-item">
				<div class="buttons">
					<a class="button" href=" {{ url_for('auth.logout')}} ">Log Out</a>
				</div>
			</div>
		{% else %}
			<div class="navbar-item">
				<div class="buttons">
					<a class="button" href=" {{ url_for('auth.register')}} ">Register</a>
					<a class="button" href=" {{ url_for('auth.login')}} ">Log In</a>
				</div>
			</div>
		{% endif %}
	</div>
</nav>
<section>
	<header>
		{% block header %}{% endblock %}
	</header>
	{% for message in get_flashed_messages() %}
		<div class="flash">{{ message }}</div>
	{% endfor %}
	{% block content %}{% endblock %}
</section>

web_app/templates/baseAdmin.html
<!DOCTYPE HTML>
<title>{% block title %}{% endblock %} - Ford Glass</title>
<link rel="stylesheet" href="{{ url_for('static', filename='bulma.min.css')}}">
<!-- Font Awesome 5 -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/css/all.min.css">
<!-- Bulma-Social -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-social@1/bin/bulma-social.min.css">
<!-- Custom CSS code -->
<link rel="stylesheet" href="{{ url_for('static', filename='style.css')}}">
<script
  src="https://code.jquery.com/jquery-3.5.1.min.js"
  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
  crossorigin="anonymous"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/jQueryNavbar.js')}}"></script>
<meta name="viewport" content="width=device-width, initial-scale=1">
<nav class="navbar" role="navigation" aria-label="main navigation">
	<div class="navbar-brand">
		<h1 class="navbar-item"><a class="action" href="{{ url_for('home.index') }}">Ford Glass</a></h1>

		<a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="admin-navbar">
			<span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
	</div>

	{% if g.user %}
	<div id="admin-navbar" class="navbar-menu">
		<div class="navbar-start">
			<a class="navbar-item action" href="{{ url_for('cms.index') }}">
        Item Management
      </a>
      <a class="navbar-item action" href="{{ url_for('cms.create') }}">
        Create Item
      </a>

      <div class="navbar-item has-dropdown is-hoverable">
      	<a class="navbar-link" href="{{ url_for('category.createcategory') }}">
          Category Management
        </a>
        <div class="navbar-dropdown is-boxed">
        	<a class="navbar-item" href="{{ url_for('category.createcategory') }}">
            Create Category
          </a>
          <a class="navbar-item" href="{{ url_for('category.updatecategory') }}">
            Update Category
          </a>
          <a class="navbar-item" href="{{ url_for('category.deletecategory') }}">
            Delete Category
          </a>
        </div>
      </div>
		</div>

		<div class="navbar-end">
				<span class="navbar-item">{{ g.user['username'] }} </span>
				<div class="navbar-item">
					<div class="buttons">
						<a class="button" href=" {{ url_for('auth.logout')}} ">Log Out</a>
					</div>
				</div>
	{% endif %}
		</div>
	</div>
</nav>
<section>
	<header>
		{% block header %}{% endblock %}
	</header>
	{% for message in get_flashed_messages() %}
		<div class="flash">{{ message }}</div>
	{% endfor %}
	{% block content %}{% endblock %}
</section>

web_app/templates/baseUser.html
<!DOCTYPE HTML>
<html>
	<head>
		{% block head %}
		<title>{% block title %}{% endblock %} - Ford Glass</title>
		<!-- Bulma CSS -->
		<link rel="stylesheet" href="{{ url_for('static', filename='bulma.min.css')}}">
		<!-- Font Awesome 5 -->
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/css/all.min.css">
		<!-- Bulma-Social -->
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-social@1/bin/bulma-social.min.css">
		<!-- Custom CSS Code -->
		<link rel="stylesheet" href="{{ url_for('static', filename='style.css')}}">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- Navigation bar code -->
		<nav class="navbar" role="navigation" aria-label="main navigation">
				<div class="navbar-brand">
				<!-- Icon here -->
				<a class="navbar-item" href="/">
			      <img src="" width="" height="">
			  </a>

				<h1 class="navbar-item title">Ford Glass</h1>
			</div>
			<div class="navbar-menu">
				<div class="navbar-end">
					<div class="navbar-item">
						<!-- Instagram Logo & Link -->
						<a class="button is-normal is-instagram" href="https://www.instagram.com/ford.glass/">
					    <span class="icon">
					      <i class="fab fa-instagram fa-lg"></i>
					    </span>
						</a>
					</div>
				</div>
			</div>
		</nav>
		{% endblock %}
	</head>

	<body> 
		<!-- Main content -->
		<div id="content">{% block content %}{% endblock %}</div>
		<!-- Footer Code -->
		<footer class="footer">
			{% block footer %}
		  <div class="columns is-multiline is-mobile">
		  	<div class="column is-half">
		    	<div class="content has-text-centered">
		    		<p>Ford Glass is a company by Henrik F Jorgensen.</p>
		    	</div>
		  	</div>
		  	<div class="column is-half">
		    	<div class="has-text-centered">
		    		<h1>Social Media</h1>
		    		<!-- Instagram Logo & Link -->
						<a class="button is-normal is-instagram" href="https://www.instagram.com/ford.glass/">
					    <span class="icon">
					      <i class="fab fa-instagram fa-lg"></i>
					    </span>
						</a>
		    	</div>
		  	</div>
		  </div>
		  {% endblock %}
		</footer>
	</body>
</html>

web_app/templates/home.html
{% extends 'baseUser.html' %}

{% block header %}
	<h1>{% block title %}Welcome{% endblock %}</h1>
{% endblock %}

{% block content %}
	<!-- Picture gallery -->
	<div class="columns is-multiline is-desktop">
		<div class="column is-full is-centered has-text-centered">
			<h1>Gallery</h1>
		</div>

	{% for item in items %}
		{% if item['category'] == 'gallery' %}
			<div class="column is-one-third">
				<header>
					<div>
						<h1>{{ item['item_name'] }}</h1>
						<p>Category: {{ item['category'] }} Sub-category: {{ item['sub_category'] }} </p>
					</div>
				</header>
				<figure class="image is-square">
					<img src="/static/images/{{ item['picture_url'] }}">
				</figure>
				<div>
					<p>{{ item['description'] }}</p>
					<p>Posted: {{ item['created'].strftime('%Y-%m-%d') }}</p>
				</div>
			</div>
		{% endif %}
	{% endfor %}

	</div>

	<div class="columns is-multiline is-desktop">
		<div class="column is-full is-centered has-text-centered">
			<h1>Jewelry</h1>
		</div>

	{% for item in items %}
		{% if item['category'] == 'jewelry' %}
			<div class="column is-one-third">
				<header>
					<div>
						<h1>{{ item['item_name'] }}</h1>
						<p>Category: {{ item['category'] }} Sub-category: {{ item['sub_category'] }} </p>
					</div>
				</header>
				<figure class="image is-square">
					<img src="/static/images/{{ item['picture_url'] }}">
				</figure>
				<div>
					<p>{{ item['description'] }}</p>
					<p>Posted: {{ item['created'].strftime('%Y-%m-%d') }}</p>
				</div>
			</div>
		{% endif %}
	{% endfor %}

	</div>

	<div class="columns is-multiline is-desktop">
		<div class="column is-full is-centered has-text-centered">
			<h1>Paraphernalia</h1>
		</div>

	{% for item in items %}
		{% if item['category'] == 'paraphernalia' %}
			<div class="column is-one-third">
				<header>
					<div>
						<h1>{{ item['item_name'] }}</h1>
						<p>Category: {{ item['category'] }} Sub-category: {{ item['sub_category'] }} </p>
					</div>
				</header>
				<figure class="image is-square">
					<img src="/static/images/{{ item['picture_url'] }}">
				</figure>
				<div>
					<p>{{ item['description'] }}</p>
					<p>Posted: {{ item['created'].strftime('%Y-%m-%d') }}</p>
				</div>
			</div>
		{% endif %}
	{% endfor %}
	</div>
	<!-- End of picture gallery -->

	<!-- Contact form -->
	<div class="contact-us-form-container columns">
		<div class="column is-full is-centered has-text-centered">
			<h1>Contact us for pricing</h1>

			<form class="control" method="post" enctype="multipart/form-data">
			 
				<div class="field">
				  <label class="label" for="visitor_name">Name</label>
				  <div class="control">
				    <input class="input" type="text" placeholder="Your name here" id="visitor_name" name="visitor_name">
				  </div>
				</div>

				<div class="field">
				  <label class="label" for="visitor_email">Email</label>
				  <div class="control has-icons-left has-icons-right">
				    <input class="input" type="email" placeholder="your-email-here@provider.com" id="visitor_email" name="visitor_email">
				    <span class="icon is-small is-left">
				      <i class="fas fa-envelope"></i>
				    </span>
				  </div>
				</div>

				<div class="field">
				  <label class="label" for="visitor_subject">Subject</label>
				  <div class="control">
				    <div class="select">
				      <select id="visitor_subject" name="visitor_subject">
				        <option>Individual pricing</option>
				        <option>Bulk pricing</option>
				        <option>Custom order</option>
				      </select>
				    </div>
				  </div>
				</div>

				<div class="field">
				  <label class="label" for="visitor_message">Message</label>
				  <div class="control">
				    <textarea class="textarea" placeholder="Enter message here" id="visitor_message" name="visitor_message"></textarea>
				  </div>
				</div>

				<div class="field is-grouped">
				  <div class="control">
				    <button class="button is-link" type="submit">Submit</button>
				  </div>
				</div>

			</form>
		</div>
	</div>
	<!-- End form -->

	<!-- For reference, delete in post
	<div class="columns is-mobile is-centered">
	{% for item in items %}
		<div class="column is-half">
			<header>
				<div>
					<h1>{{ item['item_name'] }}</h1>
					<p>Category: {{ item['category'] }} Sub-category: {{ item['sub_category'] }} </p>
				</div>
			</header>
			<figure class="image is-square">
				<img src="/static/images/{{ item['picture_url'] }}">
			</figure>
			<div>
				<p>{{ item['description'] }}</p>
				<p>Posted: {{ item['created'].strftime('%Y-%m-%d') }}</p>
			</div>
		</div>
		{% if not loop.last %}
			<hr>
		{% endif %}
	{% endfor %}
	</div>
	-->
{% endblock %}